version: '3.1'

services:

  frontend:
    container_name: frontend
    image: registry-1.docker.io/viorelspinu/docker_frontend:latest
    restart: always    
    ports:
      - 81:81
    networks:
      - network1

  backend:
    container_name: backend
    image: registry-1.docker.io/viorelspinu/docker_backend:latest
    restart: always    
    env_file:
      - ./environment-variables.env
    networks:
      - network1

  db:
    image: mysql
    container_name: db_server
    restart: always    
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./environment-variables.env
    ports:
      - 3306:3306
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - network1

networks:
  network1:
    ipam:
      config:
        - subnet: 10.5.0.0/16