version: '3.1'

services:

  frontend:
    container_name: frontend
    ports:
      - 81:81
    restart: always
    build:
      context: ../todo-frontend/
    networks:
      - network1

  backend:
    container_name: backend
    env_file:
      - ./environment-variables.env
    restart: always      
    build:
      context: ../todo-service/
    networks:
      - network1

  db:
    image: mysql
    container_name: db_server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./environment-variables.env
    ports:
      - 3306:3306
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - network1

networks:
  network1:
    ipam:
      config:
        - subnet: 10.5.0.0/16